[package]
name = "goblin"
version = "0.0.12"
authors = ["m4b <m4b.github.io@gmail.com>", "seu <seu@panopticon.re>", "Will Glynn <will@willglynn.com>"]
readme = "README.md"
keywords = ["binary", "elf", "mach", "pe", "archive"]
repository = "https://github.com/m4b/goblin"
license = "MIT"
description = "An impish, cross-platform binary parsing and loading crate"
documentation = "https://docs.rs/goblin"
categories = ["parsing"]
include = ["src/**/*", "Cargo.toml", "CHANGELOG.md", "LICENSE", "README.md", "etc/*", "examples/*", "tests/*", "fuzz/**/*"]

[lib]

[dev-dependencies]
env_logger = "0.4.3"

[dependencies]
bitflags = "1.0.1"
plain = "0.2.1"
log = { version = "0.3.8", optional = true }

[dependencies.scroll]
version = "0.7.0"
default_features = false

[dependencies.scroll_derive]
version = "0.8.0"
optional = true

[features]
default = ["std", "elf32", "elf64", "mach32", "mach64", "pe32", "pe64", "goblin", "endian_fd", "archive", "scroll/std"]
std = ["scroll/std", "scroll_derive", "log"]
endian_fd = ["std"]
elf32 = []
elf64 = []
# for now we will require mach and pe to be std + endian_fd
mach32 = ["std", "endian_fd"]
mach64 = ["std", "endian_fd"]
pe32 = ["std", "endian_fd"]
pe64 = ["std", "endian_fd"]
archive = ["endian_fd"]
goblin = []

# [profile.dev]
# opt-level = 0
# debug = true
# rpath = false
# lto = false
# debug-assertions = true
# codegen-units = 4

[badges.travis-ci]
branch = "master"
repository = "m4b/goblin"
